package br.com.itbn.sisdent.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Provides the metadata exposed by Springdoc at {@code /v3/api-docs} and in
 * Swagger UI.
 *
 * <p>This configuration is not referenced directly by application code.
 * {@link Configuration} makes it discoverable through Spring Boot component
 * scanning, and Springdoc obtains the {@link OpenAPI} bean from the Spring
 * application context when generating the API contract.</p>
 */
@Configuration
public class OpenApiConfiguration {

    /**
     * Customizes the OpenAPI contract generated by Springdoc.
     *
     * @return the API metadata registered in the Spring application context
     */
    @Bean
    @SuppressWarnings("unused") // Invoked by Spring through the @Bean lifecycle.
    OpenAPI sisdentOpenApi() {
        return new OpenAPI()
                .components(new Components().addSecuritySchemes(
                        "bearerAuth",
                        new SecurityScheme()
                                .type(SecurityScheme.Type.HTTP)
                                .scheme("bearer")
                                .bearerFormat("JWT")))
                .addSecurityItem(new SecurityRequirement().addList("bearerAuth"))
                .info(new Info()
                        .title("Sisdent API")
                        .version("v1")
                        .description(
                                "Authenticated REST API for managing patients, users, permissions, countries, addresses, and states."));
    }
}
