package br.com.itbn.sisdent.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Provides the metadata exposed by Springdoc at {@code /v3/api-docs} and in
 * Swagger UI.
 *
 * <p>This configuration is not referenced directly by application code.
 * {@link Configuration} makes it discoverable through Spring Boot component
 * scanning, and Springdoc obtains the {@link OpenAPI} bean from the Spring
 * application context when generating the API contract.</p>
 */
@Configuration
public class OpenApiConfiguration {

    /**
     * Customizes the OpenAPI contract generated by Springdoc.
     *
     * @return the API metadata registered in the Spring application context
     */
    @Bean
    @SuppressWarnings("unused") // Invoked by Spring through the @Bean lifecycle.
    OpenAPI sisdentOpenApi() {
        return new OpenAPI()
                .info(new Info()
                        .title("Sisdent API")
                        .version("v1")
                        .description("API REST para gerenciamento de pacientes, endereços e estados."));
    }
}
