package br.com.itbn.sisdent.service;
import br.com.itbn.sisdent.dto.*; import br.com.itbn.sisdent.model.*; import br.com.itbn.sisdent.repository.*; import org.springframework.data.domain.*; import org.springframework.http.*; import org.springframework.stereotype.*; import org.springframework.transaction.annotation.*; import org.springframework.web.server.*; import java.time.*; import java.util.*;
@Service public class AppointmentService { private final AppointmentRepository appointments; private final PractitionerRepository practitioners; private final ClinicUnitRepository clinics; private final PatientOrganizationLinkRepository links; private final OrganizationRepository organizations; private final ScopeAuthorizationService authorization;
 public AppointmentService(AppointmentRepository a,PractitionerRepository p,ClinicUnitRepository c,PatientOrganizationLinkRepository l,OrganizationRepository o,ScopeAuthorizationService z){appointments=a;practitioners=p;clinics=c;links=l;organizations=o;authorization=z;}
 @Transactional(readOnly=true) public PageResponse<AppointmentResponse> list(UUID org,UUID clinic,Instant from,Instant to,int page,int size){authorization.requireAppointmentRead(org,clinic);validRange(from,to);if(clinic!=null)authorization.requireClinicInOrganization(org,clinic);return PageResponse.from(appointments.findScoped(org,clinic,from,to,PageRequest.of(page,Math.min(size,100),Sort.by("startAt"))),this::response);}
 @Transactional public AppointmentResponse create(UUID org,AppointmentRequest r){authorization.requireAppointmentManagement(org,r.clinicUnitId());valid(r);Organization o=organizations.findByGlobalId(org).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));ClinicUnit c=authorization.requireClinicInOrganization(org,r.clinicUnitId());Practitioner p=lockActive(org,r.practitionerId());PatientOrganizationLink link=links.findFirstByPatient_GlobalIdAndOrganization_GlobalId(r.patientId(),org).filter(PatientOrganizationLink::isActive).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));conflict(p,r.startAt(),r.endAt(),null);return response(appointments.save(new Appointment(o,c,link,p,r.startAt(),r.endAt(),zone(r.schedulingTimezone()))));}
 @Transactional(readOnly=true) public AppointmentResponse get(UUID org,UUID clinic,UUID id){authorization.requireAppointmentRead(org,clinic);Appointment a=require(org,id);checkClinic(a,clinic);return response(a);}
 @Transactional public AppointmentResponse reschedule(UUID org,UUID id,AppointmentRequest r){authorization.requireAppointmentManagement(org,r.clinicUnitId());valid(r);Appointment a=require(org,id);checkClinic(a,r.clinicUnitId());Practitioner p=lockActive(org,a.getPractitioner().getGlobalId());if(!p.getId().equals(a.getPractitioner().getId()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Practitioner cannot be changed when rescheduling");conflict(p,r.startAt(),r.endAt(),a.getId());a.reschedule(r.startAt(),r.endAt(),zone(r.schedulingTimezone()));return response(a);}
 @Transactional public AppointmentResponse transition(UUID org,UUID clinic,UUID id,AppointmentStatus status){authorization.requireAppointmentManagement(org,clinic);Appointment a=require(org,id);checkClinic(a,clinic);try{a.transition(status);}catch(IllegalStateException e){throw new ResponseStatusException(HttpStatus.CONFLICT,"Invalid appointment state transition");}return response(a);}
 private Appointment require(UUID org,UUID id){return appointments.findByGlobalIdAndOrganization_GlobalId(id,org).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));} private Practitioner lockActive(UUID org,UUID id){Practitioner p=practitioners.lockByGlobalIdAndOrganization_GlobalId(id,org).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));if(!p.isActive())throw new ResponseStatusException(HttpStatus.CONFLICT,"Practitioner is inactive");return p;} private void conflict(Practitioner p,Instant s,Instant e,Long exclude){if(appointments.hasOverlap(p.getId(),s,e,exclude))throw new SchedulingConflictException();} private void valid(AppointmentRequest r){validRange(r.startAt(),r.endAt());zone(r.schedulingTimezone());} private void validRange(Instant s,Instant e){if(s==null||e==null||!e.isAfter(s))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Appointment end must be after start");} private String zone(String z){try{return ZoneId.of(z.strip()).getId();}catch(Exception e){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"A valid IANA timezone is required");}} private void checkClinic(Appointment a,UUID clinic){if(clinic!=null&&!a.getClinicUnit().getGlobalId().equals(clinic))throw new ResponseStatusException(HttpStatus.NOT_FOUND);} private AppointmentResponse response(Appointment a){return new AppointmentResponse(a.getGlobalId(),a.getClinicUnit().getGlobalId(),a.getPatientLink().getPatient().getGlobalId(),a.getPatientLink().getPatient().getName(),a.getPractitioner().getGlobalId(),a.getPractitioner().getDisplayName(),a.getStartAt(),a.getEndAt(),a.getSchedulingTimezone(),a.getStatus());}}
