import { Component } from '@angular/core';
import { DataTableColumn } from '../../shared/data-table/data-table.models';
import { FormDialogValues } from '../../shared/dialogs/form-dialog-shell/form-dialog-shell.models';
import { CatalogueListController } from '../resource-support/catalogue-list.controller';
import { RESOURCE_PAGE_IMPORTS } from '../resource-support/resource-page.imports';
import { ResourceRecord } from '../resource-support/resource-list.controller';

const COLUMNS: readonly DataTableColumn[] = [{ key: 'street', label: 'Street', sortable: true }, { key: 'district', label: 'District', sortable: true }, { key: 'postalCode', label: 'Postal code', sortable: true }, { key: 'administrativeDivision', label: 'Administrative division' }, { key: 'country', label: 'Country' }, { key: 'actions', label: '' }];
const FIELDS = [{ key: 'street', label: 'Street', required: true }, { key: 'district', label: 'District' }, { key: 'city', label: 'City', required: true }, { key: 'additionalInfo', label: 'Additional information' }, { key: 'block', label: 'Block' }, { key: 'postalCode', label: 'Postal code', required: true }, { key: 'administrativeDivisionName', label: 'Administrative division name' }, { key: 'administrativeDivisionCode', label: 'Administrative division code' }, { key: 'administrativeDivisionType', label: 'Administrative division type' }, { key: 'countryCode', label: 'Country code', required: true }] as const;
@Component({ selector: 'app-addresses', imports: [...RESOURCE_PAGE_IMPORTS], templateUrl: '../resource-support/resource-page.component.html', styleUrl: '../resource-support/resource-page.component.scss' })
export class AddressesComponent extends CatalogueListController {
  readonly activeKey = 'addresses'; readonly title = 'MODULES.ADDRESSES'; readonly description = 'MODULES.ADDRESSES_DESCRIPTION'; readonly translationPrefix = 'RESOURCE'; readonly columns = COLUMNS;
  constructor() { super({ endpoint: () => '/api/addresses', maintainPermission: 'MAINTAIN_ADDRESSES', columns: COLUMNS, identifier: (record) => Number(record['id']), primary: (record) => String(record['street'] ?? '—'), cells: addressCells }, { fields: FIELDS, fromRecord: addressValues, toRequest: addressRequest, title: (editing) => editing ? 'Edit address' : 'New address' }); this.load(); }
}
function nested(record: ResourceRecord, key: string): ResourceRecord { const value = record[key]; return value && typeof value === 'object' && !Array.isArray(value) ? value as ResourceRecord : {}; }
function addressCells(record: ResourceRecord): Readonly<Record<string, string>> { return { street: String(record['street'] ?? '—'), district: String(record['district'] ?? '—'), postalCode: String(record['postalCode'] ?? '—'), administrativeDivision: String(nested(record, 'administrativeDivision')['name'] ?? '—'), country: String(nested(record, 'country')['name'] ?? '—') }; }
function addressValues(record: ResourceRecord): FormDialogValues { const division = nested(record, 'administrativeDivision'); const country = nested(record, 'country'); return { street: String(record['street'] ?? ''), district: String(record['district'] ?? ''), city: String(record['city'] ?? ''), additionalInfo: String(record['additionalInfo'] ?? ''), block: String(record['block'] ?? ''), postalCode: String(record['postalCode'] ?? ''), administrativeDivisionName: String(division['name'] ?? ''), administrativeDivisionCode: String(division['code'] ?? ''), administrativeDivisionType: String(division['type'] ?? ''), countryCode: String(country['code'] ?? '') }; }
function addressRequest(value: FormDialogValues): unknown { return { street: value['street'], district: value['district'], city: value['city'], additionalInfo: value['additionalInfo'] || null, block: value['block'] || null, postalCode: value['postalCode'], administrativeDivision: value['administrativeDivisionCode'] ? { name: value['administrativeDivisionName'], code: value['administrativeDivisionCode'], type: value['administrativeDivisionType'] } : null, countryCode: value['countryCode'] }; }
