package br.com.itbn.sisdent.service;
import br.com.itbn.sisdent.model.*; import br.com.itbn.sisdent.repository.*; import java.time.*; import java.util.*; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import org.springframework.web.server.ResponseStatusException; import static org.assertj.core.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class AppointmentAvailabilityServiceTest {
 @Mock ClinicUnitWorkingHoursRepository hours; @Mock ClinicUnitBreakRepository breaks; @Mock AppointmentBlockedPeriodRepository blocked; @Mock AppointmentRepository appointments; @Mock PractitionerRepository practitioners; @Mock ScopeAuthorizationService authorization; @InjectMocks AppointmentAvailabilityService service;
 final UUID org=UUID.randomUUID(), clinicId=UUID.randomUUID(), practitionerId=UUID.randomUUID(); final Instant start=Instant.parse("2026-03-29T08:00:00Z"), end=Instant.parse("2026-03-29T09:00:00Z"); ClinicUnit clinic; Practitioner practitioner;
 @BeforeEach void set(){clinic=mock(ClinicUnit.class);practitioner=mock(Practitioner.class);lenient().when(practitioner.isActive()).thenReturn(true);lenient().when(clinic.getId()).thenReturn(2L);lenient().when(clinic.getGlobalId()).thenReturn(clinicId);lenient().when(clinic.getTimezone()).thenReturn("Europe/Lisbon");lenient().when(practitioner.getId()).thenReturn(3L);lenient().when(practitioner.getGlobalId()).thenReturn(practitionerId);lenient().when(hours.findAllByClinicUnit_Id(2L)).thenReturn(List.of(new ClinicUnitWorkingHours(clinic,7,0,1440)));lenient().when(breaks.findAllByClinicUnit_Id(2L)).thenReturn(List.of());lenient().when(blocked.findOverlapping(any(),any(),any(),any(),any())).thenReturn(List.of());lenient().when(appointments.findScheduledOverlapping(any(),any(),any(),any(),any())).thenReturn(List.of());lenient().when(appointments.hasOverlap(anyLong(),any(),any(),isNull())).thenReturn(false);}
 @Test void returnsWorkingHoursAndOccupiedBackgroundIntervalsAcrossDst(){Appointment occupied=new Appointment(new Organization("A"),clinic,mock(PatientOrganizationLink.class),practitioner,start,end,"Europe/Lisbon");when(authorization.requireClinicInOrganization(org,clinicId)).thenReturn(clinic);when(practitioners.findByGlobalIdAndOrganization_GlobalId(practitionerId,org)).thenReturn(Optional.of(practitioner));when(appointments.findScheduledOverlapping(org,clinicId,practitionerId,start,end)).thenReturn(List.of(occupied));assertThat(service.list(org,clinicId,start,end,List.of(practitionerId))).extracting(x->x.category()).containsExactlyInAnyOrder(br.com.itbn.sisdent.dto.AppointmentAvailabilityResponse.Category.WORKING_HOURS,br.com.itbn.sisdent.dto.AppointmentAvailabilityResponse.Category.OCCUPIED);}
 @Test void rejectsOutsideHoursAndBreaksAndBadRanges(){when(hours.findAllByClinicUnit_Id(2L)).thenReturn(List.of(new ClinicUnitWorkingHours(clinic,7,600,660)));assertThatThrownBy(()->service.requireAvailable(org,clinic,practitioner,start,end,null)).isInstanceOf(SchedulingConflictException.class);when(hours.findAllByClinicUnit_Id(2L)).thenReturn(List.of(new ClinicUnitWorkingHours(clinic,7,0,1440)));when(breaks.findAllByClinicUnit_Id(2L)).thenReturn(List.of(new ClinicUnitBreak(clinic,7,480,600)));assertThatThrownBy(()->service.requireAvailable(org,clinic,practitioner,start,end,null)).isInstanceOf(SchedulingConflictException.class);assertThatThrownBy(()->service.list(org,clinicId,end,start,List.of())).isInstanceOf(ResponseStatusException.class);}
 @Test void rejectsBlockedAndOccupiedIntervals(){when(blocked.findOverlapping(org,clinicId,practitionerId,start,end)).thenReturn(List.of(mock(AppointmentBlockedPeriod.class)));assertThatThrownBy(()->service.requireAvailable(org,clinic,practitioner,start,end,null)).isInstanceOf(SchedulingConflictException.class);when(blocked.findOverlapping(org,clinicId,practitionerId,start,end)).thenReturn(List.of());when(appointments.hasOverlap(3L,start,end,null)).thenReturn(true);assertThatThrownBy(()->service.requireAvailable(org,clinic,practitioner,start,end,null)).isInstanceOf(SchedulingConflictException.class);}
}
