package br.com.itbn.sisdent.error;

/**
 * Stable, locale-independent identifiers for errors exposed by application transports.
 *
 * <p>Clients must use {@link #value()} rather than matching a localized title or detail.</p>
 */
public enum ErrorCode {
    RESOURCE_NOT_FOUND("RESOURCE.NOT_FOUND"),
    VALIDATION_FAILED("VALIDATION.FAILED"),
    PAGINATION_INVALID_VALUES("PAGINATION.INVALID_VALUES"),
    PAGINATION_UNSUPPORTED_SORT("PAGINATION.UNSUPPORTED_SORT"),
    PAGINATION_UNSUPPORTED_DIRECTION("PAGINATION.UNSUPPORTED_DIRECTION"),
    SCHEDULING_PRACTITIONER_UNAVAILABLE("SCHEDULING.PRACTITIONER_UNAVAILABLE"),
    CATALOG_UNKNOWN_COUNTRY("CATALOG.UNKNOWN_COUNTRY"),
    CATALOG_UNSUPPORTED_LOCALE("CATALOG.UNSUPPORTED_LOCALE"),
    BUSINESS_RULE_VIOLATION("BUSINESS_RULE.VIOLATION"),
    CONFLICT("CONFLICT"),
    ACCOUNT_CURRENT_PASSWORD_INVALID("ACCOUNT.CURRENT_PASSWORD_INVALID"),
    ACCOUNT_PROFILE_VERSION_CONFLICT("ACCOUNT.PROFILE_VERSION_CONFLICT"),
    ACCOUNT_DISPLAY_NAME_INVALID("ACCOUNT.DISPLAY_NAME_INVALID"),
    ACCOUNT_PREFERRED_LANGUAGE_INVALID("ACCOUNT.PREFERRED_LANGUAGE_INVALID"),
    ACCOUNT_AVATAR_EMPTY("ACCOUNT.AVATAR_EMPTY"),
    ACCOUNT_AVATAR_TOO_LARGE("ACCOUNT.AVATAR_TOO_LARGE"),
    ACCOUNT_AVATAR_INVALID_TYPE("ACCOUNT.AVATAR_INVALID_TYPE"),
    ACCOUNT_AVATAR_INVALID_IMAGE("ACCOUNT.AVATAR_INVALID_IMAGE"),
    ACCOUNT_AVATAR_NOT_FOUND("ACCOUNT.AVATAR_NOT_FOUND"),
    AUTHENTICATION_FAILED("AUTHENTICATION.FAILED"),
    AUTHORIZATION_DENIED("AUTHORIZATION.DENIED"),
    INFRASTRUCTURE_FAILURE("INFRASTRUCTURE.FAILURE"),
    REQUEST_MALFORMED("REQUEST.MALFORMED"),
    REQUEST_PARAMETER_INVALID("REQUEST.PARAMETER_INVALID"),
    INTERNAL_ERROR("INTERNAL.ERROR");

    private final String value;

    ErrorCode(String value) {
        this.value = value;
    }

    public String value() {
        return value;
    }
}
