package br.com.itbn.sisdent.model;
import jakarta.persistence.*; import java.time.*; import java.util.*;
@Entity @Table(name="clinical_encounters") public class ClinicalEncounter extends AuditableEntity {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id; @Column(name="global_id",nullable=false,unique=true,updatable=false) private UUID globalId=UUID.randomUUID();
 @ManyToOne(fetch=FetchType.LAZY,optional=false) private Organization organization; @ManyToOne(fetch=FetchType.LAZY,optional=false) private ClinicUnit clinicUnit; @ManyToOne(fetch=FetchType.LAZY,optional=false) private PatientOrganizationLink patientLink; @ManyToOne(fetch=FetchType.LAZY) private Appointment appointment; @ManyToOne(fetch=FetchType.LAZY) private Practitioner practitioner; @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="original_encounter_id") private ClinicalEncounter originalEncounter;
 private Instant careAt; private String careTimezone; @Column(length=4000) private String narrative; @Column(length=500) private String administrativeNote; @Enumerated(EnumType.STRING) private EncounterStatus status=EncounterStatus.DRAFT; private Instant finalizedAt; private String finalizedBy; @Column(length=500) private String amendmentReason;
 protected ClinicalEncounter(){} public ClinicalEncounter(Organization o,ClinicUnit c,PatientOrganizationLink p,Appointment a,Practitioner r,Instant at,String zone,String n,String note,ClinicalEncounter original,String reason){organization=o;clinicUnit=c;patientLink=p;appointment=a;practitioner=r;careAt=at;careTimezone=zone;narrative=n;administrativeNote=note;originalEncounter=original;amendmentReason=reason;}
 public Long getId(){return id;} public UUID getGlobalId(){return globalId;} public Organization getOrganization(){return organization;} public ClinicUnit getClinicUnit(){return clinicUnit;} public PatientOrganizationLink getPatientLink(){return patientLink;} public Appointment getAppointment(){return appointment;} public Practitioner getPractitioner(){return practitioner;} public ClinicalEncounter getOriginalEncounter(){return originalEncounter;} public Instant getCareAt(){return careAt;} public String getCareTimezone(){return careTimezone;} public String getNarrative(){return narrative;} public String getAdministrativeNote(){return administrativeNote;} public EncounterStatus getStatus(){return status;} public Instant getFinalizedAt(){return finalizedAt;} public String getFinalizedBy(){return finalizedBy;} public String getAmendmentReason(){return amendmentReason;}
 public void update(Instant at,String zone,String n,String note,Practitioner p,Appointment a){if(status!=EncounterStatus.DRAFT)throw new IllegalStateException();careAt=at;careTimezone=zone;narrative=n;administrativeNote=note;practitioner=p;appointment=a;} public void finalizeRecord(String actor){if(status!=EncounterStatus.DRAFT)throw new IllegalStateException();status=EncounterStatus.FINAL;finalizedAt=Instant.now();finalizedBy=actor;}
}
