package br.com.itbn.sisdent.model;

public enum MembershipRole {
    ORGANIZATION_ADMIN,
    MANAGER,
    READ_ONLY,
    PRACTITIONER_MANAGER,
    APPOINTMENT_MANAGER,
    APPOINTMENT_READER,
    CLINICAL_READER,
    CLINICAL_AUTHOR,
    CLINICAL_MANAGER
}
