ALTER TABLE memberships DROP CONSTRAINT ck_memberships_role;
ALTER TABLE memberships ADD CONSTRAINT ck_memberships_role CHECK (role IN (
 'ORGANIZATION_ADMIN', 'MANAGER', 'READ_ONLY', 'PRACTITIONER_MANAGER', 'APPOINTMENT_MANAGER', 'APPOINTMENT_READER'));
ALTER TABLE patient_organization_links ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE practitioners (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 global_id UUID DEFAULT RANDOM_UUID() NOT NULL,
 organization_id BIGINT NOT NULL, account_id BIGINT, display_name VARCHAR(255) NOT NULL,
 registration_number VARCHAR(128), active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by VARCHAR(255) NOT NULL DEFAULT 'migration-v10',
 updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by VARCHAR(255) NOT NULL DEFAULT 'migration-v10', version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT uk_practitioners_global_id UNIQUE (global_id),
 CONSTRAINT uk_practitioners_organization_registration UNIQUE (organization_id, registration_number),
 CONSTRAINT fk_practitioners_organization FOREIGN KEY (organization_id) REFERENCES organizations(id),
 CONSTRAINT fk_practitioners_account FOREIGN KEY (account_id) REFERENCES accounts(id));
CREATE TABLE practitioner_specialities (practitioner_id BIGINT NOT NULL, speciality_id BIGINT NOT NULL,
 CONSTRAINT pk_practitioner_specialities PRIMARY KEY (practitioner_id, speciality_id),
 CONSTRAINT fk_practitioner_specialities_practitioner FOREIGN KEY (practitioner_id) REFERENCES practitioners(id),
 CONSTRAINT fk_practitioner_specialities_speciality FOREIGN KEY (speciality_id) REFERENCES specialities(id));
CREATE TABLE appointments (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, global_id UUID DEFAULT RANDOM_UUID() NOT NULL,
 organization_id BIGINT NOT NULL, clinic_unit_id BIGINT NOT NULL, patient_link_id BIGINT NOT NULL, practitioner_id BIGINT NOT NULL,
 start_at TIMESTAMP WITH TIME ZONE NOT NULL, end_at TIMESTAMP WITH TIME ZONE NOT NULL, scheduling_timezone VARCHAR(64) NOT NULL, status VARCHAR(16) NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by VARCHAR(255) NOT NULL DEFAULT 'migration-v10',
 updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by VARCHAR(255) NOT NULL DEFAULT 'migration-v10', version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT uk_appointments_global_id UNIQUE (global_id), CONSTRAINT ck_appointments_interval CHECK (end_at > start_at),
 CONSTRAINT ck_appointments_status CHECK (status IN ('SCHEDULED','CANCELLED','COMPLETED','NO_SHOW')),
 CONSTRAINT fk_appointments_organization FOREIGN KEY (organization_id) REFERENCES organizations(id),
 CONSTRAINT fk_appointments_clinic FOREIGN KEY (clinic_unit_id) REFERENCES clinic_units(id),
 CONSTRAINT fk_appointments_patient_link FOREIGN KEY (patient_link_id) REFERENCES patient_organization_links(id),
 CONSTRAINT fk_appointments_practitioner FOREIGN KEY (practitioner_id) REFERENCES practitioners(id));
CREATE INDEX idx_appointments_scope_time ON appointments(organization_id, clinic_unit_id, start_at);
CREATE INDEX idx_appointments_practitioner_schedule ON appointments(practitioner_id, status, start_at, end_at);
CREATE TABLE performed_procedures (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, global_id UUID DEFAULT RANDOM_UUID() NOT NULL,
 appointment_id BIGINT NOT NULL, dental_procedure_id BIGINT NOT NULL, procedure_name_snapshot VARCHAR(255) NOT NULL,
 performed_at TIMESTAMP WITH TIME ZONE NOT NULL, administrative_note VARCHAR(500), voided_at TIMESTAMP WITH TIME ZONE, voided_by VARCHAR(255), void_reason VARCHAR(500),
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by VARCHAR(255) NOT NULL DEFAULT 'migration-v10',
 updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by VARCHAR(255) NOT NULL DEFAULT 'migration-v10', version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT uk_performed_procedures_global_id UNIQUE(global_id),
 CONSTRAINT ck_performed_procedure_void CHECK ((voided_at IS NULL AND voided_by IS NULL AND void_reason IS NULL) OR (voided_at IS NOT NULL AND voided_by IS NOT NULL AND void_reason IS NOT NULL)),
 CONSTRAINT fk_performed_procedures_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id),
 CONSTRAINT fk_performed_procedures_catalog FOREIGN KEY (dental_procedure_id) REFERENCES dental_procedures(id));
CREATE INDEX idx_performed_procedures_appointment ON performed_procedures(appointment_id, performed_at);
