ALTER TABLE memberships DROP CONSTRAINT ck_memberships_role;
ALTER TABLE memberships ADD CONSTRAINT ck_memberships_role CHECK (role IN (
 'ORGANIZATION_ADMIN','MANAGER','READ_ONLY','PRACTITIONER_MANAGER','APPOINTMENT_MANAGER','APPOINTMENT_READER',
 'CLINICAL_READER','CLINICAL_AUTHOR','CLINICAL_MANAGER'));

CREATE TABLE clinical_encounters (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, global_id UUID DEFAULT RANDOM_UUID() NOT NULL,
 organization_id BIGINT NOT NULL, clinic_unit_id BIGINT NOT NULL, patient_link_id BIGINT NOT NULL,
 appointment_id BIGINT, practitioner_id BIGINT, original_encounter_id BIGINT,
 care_at TIMESTAMP WITH TIME ZONE NOT NULL, care_timezone VARCHAR(64) NOT NULL,
 narrative VARCHAR(4000) NOT NULL, administrative_note VARCHAR(500), status VARCHAR(16) NOT NULL,
 finalized_at TIMESTAMP WITH TIME ZONE, finalized_by VARCHAR(255), amendment_reason VARCHAR(500),
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by VARCHAR(255) NOT NULL DEFAULT 'migration-v11',
 updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by VARCHAR(255) NOT NULL DEFAULT 'migration-v11', version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT uk_clinical_encounters_global_id UNIQUE(global_id),
 CONSTRAINT ck_clinical_encounter_status CHECK (status IN ('DRAFT','FINAL')),
 CONSTRAINT ck_clinical_encounter_final CHECK ((status='DRAFT' AND finalized_at IS NULL AND finalized_by IS NULL) OR (status='FINAL' AND finalized_at IS NOT NULL AND finalized_by IS NOT NULL)),
 CONSTRAINT ck_clinical_encounter_amendment CHECK ((original_encounter_id IS NULL AND amendment_reason IS NULL) OR (original_encounter_id IS NOT NULL AND amendment_reason IS NOT NULL)),
 CONSTRAINT fk_clinical_encounter_organization FOREIGN KEY (organization_id) REFERENCES organizations(id),
 CONSTRAINT fk_clinical_encounter_clinic FOREIGN KEY (clinic_unit_id) REFERENCES clinic_units(id),
 CONSTRAINT fk_clinical_encounter_patient_link FOREIGN KEY (patient_link_id) REFERENCES patient_organization_links(id),
 CONSTRAINT fk_clinical_encounter_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id),
 CONSTRAINT fk_clinical_encounter_practitioner FOREIGN KEY (practitioner_id) REFERENCES practitioners(id),
 CONSTRAINT fk_clinical_encounter_original FOREIGN KEY (original_encounter_id) REFERENCES clinical_encounters(id));
CREATE INDEX idx_clinical_encounters_scope_patient ON clinical_encounters(organization_id, clinic_unit_id, patient_link_id, care_at);
CREATE INDEX idx_clinical_encounters_original ON clinical_encounters(original_encounter_id);

CREATE TABLE odontogram_findings (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, global_id UUID DEFAULT RANDOM_UUID() NOT NULL,
 organization_id BIGINT NOT NULL, clinic_unit_id BIGINT NOT NULL, patient_link_id BIGINT NOT NULL, practitioner_id BIGINT,
 replacement_for_id BIGINT, tooth_code VARCHAR(2) NOT NULL, surface VARCHAR(32) NOT NULL, condition_code VARCHAR(32) NOT NULL,
 observed_at TIMESTAMP WITH TIME ZONE NOT NULL, observation_timezone VARCHAR(64) NOT NULL, clinical_note VARCHAR(500),
 voided_at TIMESTAMP WITH TIME ZONE, voided_by VARCHAR(255), void_reason VARCHAR(500),
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by VARCHAR(255) NOT NULL DEFAULT 'migration-v11',
 updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by VARCHAR(255) NOT NULL DEFAULT 'migration-v11', version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT uk_odontogram_findings_global_id UNIQUE(global_id),
 CONSTRAINT ck_odontogram_tooth CHECK (tooth_code IN ('11','12','13','14','15','16','17','18','21','22','23','24','25','26','27','28','31','32','33','34','35','36','37','38','41','42','43','44','45','46','47','48','51','52','53','54','55','61','62','63','64','65','71','72','73','74','75','81','82','83','84','85')),
 CONSTRAINT ck_odontogram_surface CHECK (surface IN ('WHOLE_TOOTH','MESIAL','DISTAL','OCCLUSAL_INCISAL','BUCCAL','LINGUAL_PALATAL')),
 CONSTRAINT ck_odontogram_condition CHECK (condition_code IN ('SOUND','CARIES','RESTORATION','CROWN','MISSING','IMPLANT','EXTRACTED')),
 CONSTRAINT ck_odontogram_void CHECK ((voided_at IS NULL AND voided_by IS NULL AND void_reason IS NULL) OR (voided_at IS NOT NULL AND voided_by IS NOT NULL AND void_reason IS NOT NULL)),
 CONSTRAINT fk_odontogram_organization FOREIGN KEY (organization_id) REFERENCES organizations(id),
 CONSTRAINT fk_odontogram_clinic FOREIGN KEY (clinic_unit_id) REFERENCES clinic_units(id),
 CONSTRAINT fk_odontogram_patient_link FOREIGN KEY (patient_link_id) REFERENCES patient_organization_links(id),
 CONSTRAINT fk_odontogram_practitioner FOREIGN KEY (practitioner_id) REFERENCES practitioners(id),
 CONSTRAINT fk_odontogram_replacement FOREIGN KEY (replacement_for_id) REFERENCES odontogram_findings(id));
CREATE INDEX idx_odontogram_current ON odontogram_findings(organization_id, patient_link_id, tooth_code, surface, observed_at);
CREATE INDEX idx_odontogram_history ON odontogram_findings(organization_id, clinic_unit_id, patient_link_id, observed_at);
