CREATE TABLE catalog_translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_type VARCHAR(32) NOT NULL,
    resource_id BIGINT NOT NULL,
    locale VARCHAR(10) NOT NULL,
    translated_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by VARCHAR(255) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_catalog_translation UNIQUE (resource_type, resource_id, locale),
    CONSTRAINT ck_catalog_translation_type CHECK (resource_type IN ('SPECIALITY', 'PROCEDURE')),
    CONSTRAINT ck_catalog_translation_locale CHECK (locale IN ('en', 'pt-PT', 'nl'))
);

CREATE INDEX idx_catalog_translation_resource
    ON catalog_translations (resource_type, resource_id);
