CREATE TABLE states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    abbreviation VARCHAR(2) NOT NULL,
    CONSTRAINT uk_states_abbreviation UNIQUE (abbreviation)
);

CREATE TABLE specialities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_specialities_name UNIQUE (name)
);

CREATE TABLE addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street VARCHAR(255) NOT NULL,
    district VARCHAR(255) NOT NULL,
    additional_info VARCHAR(255),
    block VARCHAR(255),
    postal_code VARCHAR(8) NOT NULL,
    state_id BIGINT NOT NULL,
    CONSTRAINT uk_addresses_postal_code UNIQUE (postal_code),
    CONSTRAINT fk_addresses_state
        FOREIGN KEY (state_id) REFERENCES states (id)
);

CREATE TABLE patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    active BOOLEAN NOT NULL,
    gender ENUM ('FEMALE', 'MALE', 'OTHER') NOT NULL,
    tax_id VARCHAR(11) NOT NULL,
    address_id BIGINT NOT NULL,
    CONSTRAINT uk_patients_tax_id UNIQUE (tax_id),
    CONSTRAINT fk_patients_address
        FOREIGN KEY (address_id) REFERENCES addresses (id)
);

CREATE TABLE procedures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    speciality_id BIGINT NOT NULL,
    CONSTRAINT uk_procedure_speciality_name
        UNIQUE (speciality_id, name),
    CONSTRAINT fk_procedures_speciality
        FOREIGN KEY (speciality_id) REFERENCES specialities (id)
);

CREATE TABLE patient_specialities (
    patient_id BIGINT NOT NULL,
    speciality_id BIGINT NOT NULL,
    PRIMARY KEY (patient_id, speciality_id),
    CONSTRAINT fk_patient_specialities_patient
        FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT fk_patient_specialities_speciality
        FOREIGN KEY (speciality_id) REFERENCES specialities (id)
);
