ALTER TABLE clinic_units ADD COLUMN timezone VARCHAR(64) NOT NULL DEFAULT 'Europe/Lisbon';

CREATE TABLE clinic_unit_working_hours (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 clinic_unit_id BIGINT NOT NULL, day_of_week INTEGER NOT NULL, start_minute INTEGER NOT NULL, end_minute INTEGER NOT NULL,
 CONSTRAINT ck_working_hours_day CHECK (day_of_week BETWEEN 1 AND 7),
 CONSTRAINT ck_working_hours_interval CHECK (start_minute >= 0 AND end_minute <= 1440 AND end_minute > start_minute),
 CONSTRAINT fk_working_hours_clinic FOREIGN KEY (clinic_unit_id) REFERENCES clinic_units(id));
CREATE INDEX idx_working_hours_clinic_day ON clinic_unit_working_hours(clinic_unit_id, day_of_week);

CREATE TABLE clinic_unit_breaks (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 clinic_unit_id BIGINT NOT NULL, day_of_week INTEGER NOT NULL, start_minute INTEGER NOT NULL, end_minute INTEGER NOT NULL,
 CONSTRAINT ck_breaks_day CHECK (day_of_week BETWEEN 1 AND 7),
 CONSTRAINT ck_breaks_interval CHECK (start_minute >= 0 AND end_minute <= 1440 AND end_minute > start_minute),
 CONSTRAINT fk_breaks_clinic FOREIGN KEY (clinic_unit_id) REFERENCES clinic_units(id));
CREATE INDEX idx_breaks_clinic_day ON clinic_unit_breaks(clinic_unit_id, day_of_week);

CREATE TABLE appointment_blocked_periods (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, global_id UUID DEFAULT RANDOM_UUID() NOT NULL,
 organization_id BIGINT NOT NULL, clinic_unit_id BIGINT NOT NULL, practitioner_id BIGINT, start_at TIMESTAMP WITH TIME ZONE NOT NULL, end_at TIMESTAMP WITH TIME ZONE NOT NULL,
 CONSTRAINT uk_blocked_periods_global_id UNIQUE (global_id), CONSTRAINT ck_blocked_periods_interval CHECK (end_at > start_at),
 CONSTRAINT fk_blocked_periods_organization FOREIGN KEY (organization_id) REFERENCES organizations(id),
 CONSTRAINT fk_blocked_periods_clinic FOREIGN KEY (clinic_unit_id) REFERENCES clinic_units(id),
 CONSTRAINT fk_blocked_periods_practitioner FOREIGN KEY (practitioner_id) REFERENCES practitioners(id));
CREATE INDEX idx_blocked_periods_scope_time ON appointment_blocked_periods(organization_id, clinic_unit_id, start_at, end_at);

INSERT INTO clinic_unit_working_hours (clinic_unit_id, day_of_week, start_minute, end_minute)
SELECT id, d.day_of_week, 0, 1440 FROM clinic_units CROSS JOIN (VALUES (1), (2), (3), (4), (5), (6), (7)) d(day_of_week);
