CREATE TABLE countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(2) NOT NULL,
    continent ENUM ('EUROPE', 'NORTH_AMERICA', 'SOUTH_AMERICA') NOT NULL,
    CONSTRAINT uk_countries_name UNIQUE (name),
    CONSTRAINT uk_countries_code UNIQUE (code)
);

INSERT INTO countries (name, code, continent)
VALUES ('United States', 'US', 'NORTH_AMERICA');

ALTER TABLE addresses ADD COLUMN country_id BIGINT;

UPDATE addresses
SET country_id = (SELECT id FROM countries WHERE code = 'US')
WHERE country_id IS NULL;

ALTER TABLE addresses ALTER COLUMN country_id SET NOT NULL;
ALTER TABLE addresses ADD CONSTRAINT fk_addresses_country
    FOREIGN KEY (country_id) REFERENCES countries (id);

ALTER TABLE patients
    ADD COLUMN identification_type ENUM ('NATIONAL_ID', 'PASSPORT');
ALTER TABLE patients ADD COLUMN identification_number VARCHAR(64);
ALTER TABLE patients ADD COLUMN nationality_country_id BIGINT;

UPDATE patients
SET identification_type = 'NATIONAL_ID',
    identification_number = CONCAT('US', tax_id),
    nationality_country_id = (SELECT id FROM countries WHERE code = 'US')
WHERE identification_number IS NULL;

ALTER TABLE patients ALTER COLUMN identification_type SET NOT NULL;
ALTER TABLE patients ALTER COLUMN identification_number SET NOT NULL;
ALTER TABLE patients ALTER COLUMN nationality_country_id SET NOT NULL;

ALTER TABLE patients ADD CONSTRAINT uk_patients_identification_number
    UNIQUE (identification_number);
ALTER TABLE patients ADD CONSTRAINT fk_patients_nationality_country
    FOREIGN KEY (nationality_country_id) REFERENCES countries (id);
