CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identification_type ENUM ('NATIONAL_ID', 'PASSPORT') NOT NULL,
    identification_number VARCHAR(64) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM ('ADMIN', 'MANAGER', 'USER') NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_users_identification UNIQUE (identification_type, identification_number)
);

CREATE TABLE user_permissions (
    user_id BIGINT NOT NULL,
    permission ENUM ('CREATE', 'UPDATE', 'READ', 'DELETE') NOT NULL,
    PRIMARY KEY (user_id, permission),
    CONSTRAINT fk_user_permissions_user
        FOREIGN KEY (user_id) REFERENCES app_users (id)
);
