CREATE TABLE persons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    global_id UUID DEFAULT RANDOM_UUID() NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL DEFAULT 'migration-v8',
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255) NOT NULL DEFAULT 'migration-v8',
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_persons_global_id UNIQUE (global_id)
);

CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    global_id UUID DEFAULT RANDOM_UUID() NOT NULL,
    person_id BIGINT NOT NULL,
    legacy_user_id BIGINT,
    email VARCHAR(320) NOT NULL,
    password VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    platform_administrator BOOLEAN NOT NULL DEFAULT FALSE,
    email_migration_required BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL DEFAULT 'migration-v8',
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255) NOT NULL DEFAULT 'migration-v8',
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_accounts_global_id UNIQUE (global_id),
    CONSTRAINT uk_accounts_email UNIQUE (email),
    CONSTRAINT uk_accounts_legacy_user UNIQUE (legacy_user_id),
    CONSTRAINT fk_accounts_person FOREIGN KEY (person_id) REFERENCES persons (id),
    CONSTRAINT fk_accounts_legacy_user FOREIGN KEY (legacy_user_id) REFERENCES app_users (id)
);

CREATE TABLE organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    global_id UUID DEFAULT RANDOM_UUID() NOT NULL,
    name VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL DEFAULT 'migration-v8',
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255) NOT NULL DEFAULT 'migration-v8',
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_organizations_global_id UNIQUE (global_id)
);

CREATE TABLE clinic_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    global_id UUID DEFAULT RANDOM_UUID() NOT NULL,
    organization_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL DEFAULT 'migration-v8',
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255) NOT NULL DEFAULT 'migration-v8',
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_clinic_units_global_id UNIQUE (global_id),
    CONSTRAINT uk_clinic_units_organization_name UNIQUE (organization_id, name),
    CONSTRAINT fk_clinic_units_organization FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    global_id UUID DEFAULT RANDOM_UUID() NOT NULL,
    account_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,
    clinic_unit_id BIGINT,
    role VARCHAR(32) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL DEFAULT 'migration-v8',
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255) NOT NULL DEFAULT 'migration-v8',
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_memberships_global_id UNIQUE (global_id),
    CONSTRAINT uk_memberships_scope UNIQUE (account_id, organization_id, clinic_unit_id),
    CONSTRAINT fk_memberships_account FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT fk_memberships_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_memberships_clinic_unit FOREIGN KEY (clinic_unit_id) REFERENCES clinic_units (id),
    CONSTRAINT ck_memberships_role CHECK (role IN ('ORGANIZATION_ADMIN', 'MANAGER', 'READ_ONLY'))
);

ALTER TABLE patients ADD COLUMN person_id BIGINT;
ALTER TABLE patients ADD CONSTRAINT fk_patients_person FOREIGN KEY (person_id) REFERENCES persons (id);

CREATE TABLE patient_organization_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    global_id UUID DEFAULT RANDOM_UUID() NOT NULL,
    patient_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,
    clinic_unit_id BIGINT,
    operational_basis VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL DEFAULT 'migration-v8',
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255) NOT NULL DEFAULT 'migration-v8',
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_patient_links_global_id UNIQUE (global_id),
    CONSTRAINT uk_patient_links_scope UNIQUE (patient_id, organization_id, clinic_unit_id),
    CONSTRAINT fk_patient_links_patient FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT fk_patient_links_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_patient_links_clinic_unit FOREIGN KEY (clinic_unit_id) REFERENCES clinic_units (id),
    CONSTRAINT ck_patient_links_basis CHECK (
        operational_basis IN ('BOOKING_REQUEST', 'ATTENDANCE', 'INTAKE', 'DOCUMENT_ACCEPTANCE', 'LEGACY_MIGRATION')
    )
);

INSERT INTO persons (id, display_name, created_by, updated_by)
SELECT id, CONCAT('Legacy user ', identification_type, ' ', identification_number), 'migration-v8', 'migration-v8'
FROM app_users;

INSERT INTO accounts (
    id, person_id, legacy_user_id, email, password, active,
    platform_administrator, email_migration_required, created_by, updated_by
)
SELECT
    id, id, id,
    LOWER(CONCAT(identification_type, '.', identification_number, '@legacy.sisdent.invalid')),
    password, active, CASE WHEN role = 'ADMIN' THEN TRUE ELSE FALSE END,
    TRUE, 'migration-v8', 'migration-v8'
FROM app_users;

INSERT INTO organizations (id, name, created_by, updated_by)
SELECT 1, 'Legacy Sisdent Organization', 'migration-v8', 'migration-v8'
WHERE EXISTS (SELECT 1 FROM app_users);

INSERT INTO clinic_units (id, organization_id, name, created_by, updated_by)
SELECT 1, 1, 'Legacy Clinic Unit', 'migration-v8', 'migration-v8'
WHERE EXISTS (SELECT 1 FROM app_users);

INSERT INTO memberships (
    account_id, organization_id, clinic_unit_id, role, active, created_by, updated_by
)
SELECT
    id, 1, NULL,
    CASE role
        WHEN 'ADMIN' THEN 'ORGANIZATION_ADMIN'
        WHEN 'MANAGER' THEN 'MANAGER'
        ELSE 'READ_ONLY'
    END,
    active, 'migration-v8', 'migration-v8'
FROM app_users;

INSERT INTO patient_organization_links (
    patient_id, organization_id, clinic_unit_id, operational_basis, created_by, updated_by
)
SELECT id, 1, 1, 'LEGACY_MIGRATION', 'migration-v8', 'migration-v8'
FROM patients
WHERE EXISTS (SELECT 1 FROM organizations WHERE id = 1);

CREATE INDEX idx_accounts_person ON accounts (person_id);
CREATE INDEX idx_memberships_account_active ON memberships (account_id, active);
CREATE INDEX idx_memberships_organization_clinic ON memberships (organization_id, clinic_unit_id);
CREATE INDEX idx_patient_links_organization_clinic ON patient_organization_links (organization_id, clinic_unit_id);
CREATE INDEX idx_patient_links_patient ON patient_organization_links (patient_id);
