ALTER TABLE accounts ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE accounts ADD COLUMN pending_email VARCHAR(320);
ALTER TABLE accounts ADD CONSTRAINT uk_accounts_pending_email UNIQUE (pending_email);

UPDATE accounts
SET email_verified = TRUE
WHERE email_migration_required = FALSE;

CREATE TABLE account_email_claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    normalized_email VARCHAR(320) NOT NULL,
    claim_type VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL DEFAULT 'migration-v9',
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255) NOT NULL DEFAULT 'migration-v9',
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_account_email_claims_email UNIQUE (normalized_email),
    CONSTRAINT uk_account_email_claims_account_type UNIQUE (account_id, claim_type),
    CONSTRAINT fk_account_email_claims_account FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT ck_account_email_claims_type CHECK (claim_type IN ('VERIFIED', 'PENDING'))
);

INSERT INTO account_email_claims (
    account_id, normalized_email, claim_type, created_by, updated_by
)
SELECT id, email, 'VERIFIED', 'migration-v9', 'migration-v9'
FROM accounts;

CREATE TABLE email_verification_challenges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    global_id UUID DEFAULT RANDOM_UUID() NOT NULL,
    account_id BIGINT NOT NULL,
    target_email VARCHAR(320) NOT NULL,
    secret_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE,
    delivery_provider VARCHAR(64) NOT NULL,
    delivery_message_id VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NOT NULL DEFAULT 'migration-v9',
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255) NOT NULL DEFAULT 'migration-v9',
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_email_verification_challenges_global_id UNIQUE (global_id),
    CONSTRAINT uk_email_verification_challenges_secret_hash UNIQUE (secret_hash),
    CONSTRAINT fk_email_verification_challenges_account FOREIGN KEY (account_id) REFERENCES accounts (id)
);

CREATE INDEX idx_email_verification_challenges_account_created
    ON email_verification_challenges (account_id, created_at);
CREATE INDEX idx_email_verification_challenges_account_active
    ON email_verification_challenges (account_id, consumed_at, revoked_at, expires_at);
