name: Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: maven:3.9.16-eclipse-temurin-25

    steps:
      - uses: actions/checkout@v6

      - run: mvn --batch-mode --no-transfer-progress test
